---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: app-pasta
  namespace: app-pasta
spec: 
  gateways:
  - istio-system/ingress-gateway
  hosts: 
  - v1.time-keeper.watch
  http:
  - match:
    - uri:
        prefix: /pasta
    route: 
    - destination: 
        host: app-pasta.app-pasta.svc.cluster.local
        port: 
          number: 8080

